server:
  port: 8081
  session:
  cookie:
    name: sessionid
spring:
#  redis:
#    database: 0 # Redis数据库索引（默认为0）
#    host: 114.116.252.196 # Redis服务器地址
#    #host: 127.0.0.1 # Redis服务器地址
#    port: 6379 # Redis服务器连接端口
#    password: 301626 # Redis服务器连接密码（默认为空）
#    timeout: 2000  # 连接超时时间（毫秒）
#    jedis:
#      pool:
#        max-active: 200         # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 20         # 连接池中的最大空闲连接
#        min-idle: 0         # 连接池中的最小空闲连接
#        max-wait: -1       # 连接池最大阻塞等待时间（使用负值表示没有限制）
  datasource:
    #url: jdbc:mysql://114.116.252.196:3306/myadmin?serverTimezone=GMT%2B8&useUnicode=true&useAffectedRows=true&characterEncoding=utf-8
    url: jdbc:mysql://1.12.238.58:3306/myadmin?serverTimezone=GMT%2B8&useUnicode=true&useAffectedRows=true&characterEncoding=utf-8
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: "classpath*:com/example/LqcSpringBoot/mapperXml/*.xml"
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl